# image: https://registry.hub.docker.com/r/theiaide/theia

version: '3.8'

services:
  theia:
    image: theiaide/theia:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_HTTP_PORT}:3000
    volumes:
      - theia:/home/project
    restart: always

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  theia:
